import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const response = await fetch(
  "https://api.github.com/repos/OAI/OpenAPI-Specification/contents/versions?ref=main",
  { headers: { Accept: "application/vnd.github.v3+json" } },
);
if (!response.ok) {
  throw new Error(
    `GitHub API error ${response.status}: ${await response.text()}`,
  );
}
const data: Array<{ name: string }> = await response.json();
const versions = data
  .filter(
    (item) => item.name.endsWith(".md") && !item.name.includes("-editors"),
  )
  .map((item) => item.name.replace(".md", ""));

const output = `/**
 * Auto-generated by specs-upgrade.ts
 */

const SPECS: string[] = ${JSON.stringify(versions, null, 2).replace(/\n\]/, ",\n]")};
export default SPECS;
`;

const outPath = join(
  dirname(fileURLToPath(import.meta.url)),
  "../specs.gen.ts",
);
writeFileSync(outPath, output);
console.info(outPath);
