/**
 * Auto-generated by specs-upgrade.ts
 */

const SPECS: string[] = [
  "1.2",
  "2.0",
  "3.0.0",
  "3.0.1",
  "3.0.2",
  "3.0.3",
  "3.0.4",
  "3.1.0",
  "3.1.1",
  "3.1.2",
  "3.2.0",
];
export default SPECS;
